version: '3'
services:
     coderedcryptoapi_1:
        image: onsolve/coderedcryptoapi:{FCR-coderedcryptoapi-version}
        ports:
        - "10800:10800"
        networks:
        - coderedcryptoapi_network
        environment:
        - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
        - ASPNETCORE_Kestrel__Certificates__Default__Path=aspnetapp.pfx
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:10800;http://+:10800
        - ASPNETCORE_HTTPS_PORT=10800
        env_file:
          ./.env
networks:
    coderedcryptoapi_network:
        driver: bridge
